#ifndef DistDir
  #define DistDir "dist"
#endif

#ifndef OutputDir
  #define OutputDir "."
#endif

#ifndef SetupIconFile
  #define SetupIconFile ""
#endif

[Setup]
; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only
AppId={{185C1E99-E4F0-435F-8F12-F26235213749}
AppName=Webtoon Desktop Reader
AppVersion=1.0.1
;AppVerName=Webtoon Desktop Reader 1.0.1
AppPublisher=Webtoon Desktop Reader
AppPublisherURL=https://github.com/Oeber/Webtoon-Desktop-Reader
AppSupportURL=https://github.com/Oeber/Webtoon-Desktop-Reader
AppUpdatesURL=https://github.com/Oeber/Webtoon-Desktop-Reader
DefaultDirName={autopf}\Webtoon Desktop Reader
DefaultGroupName=Webtoon Desktop Reader
UninstallDisplayIcon={app}\Webtoon Desktop Reader.exe
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
PrivilegesRequiredOverridesAllowed=dialog
Compression=lzma
SolidCompression=yes
WizardStyle=classic
OutputDir={#OutputDir}
OutputBaseFilename=Webtoon-Desktop-Reader-Setup-v1.0.1
#if SetupIconFile != ""
SetupIconFile={#SetupIconFile}
#endif

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#DistDir}\Webtoon Desktop Reader.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DistDir}\Webtoon Desktop Reader Updater.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#DistDir}\data\*"; DestDir: "{app}\data"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#DistDir}\scrapers\*"; DestDir: "{app}\scrapers"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "{#DistDir}\webtoons"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\Webtoon Desktop Reader"; Filename: "{app}\Webtoon Desktop Reader.exe"
Name: "{autodesktop}\Webtoon Desktop Reader"; Filename: "{app}\Webtoon Desktop Reader.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\Webtoon Desktop Reader.exe"; Description: "{cm:LaunchProgram,Webtoon Desktop Reader}"; Flags: nowait postinstall skipifsilent































